version: '3.8'

services:
  db:
    image: postgres:15.2
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
        - .:/app
    env_file:
      - .env
    environment:
        DATABASE_URL: ${DATABASE_URL}
        PORT: ${APP_PORT}
    tty: true
    stdin_open: true
volumes:
  pgdata: