POST http://localhost:8080/book/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Книга название
--WebAppBoundary
Content-Disposition: form-data; name="author_id"
Content-Type: text/plain

1
--WebAppBoundary
Content-Disposition: form-data; name="genre"
Content-Type: text/plain

Detective
--WebAppBoundary
Content-Disposition: form-data; name="date_published"
Content-Type: text/plain

1997-01-15
